AgriculturalSale/AgriculturalSale/Models/Location.cs
using AgriculturalSale.Data.Base;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgriculturalSale.Models
{
    public class Location: IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string SideWalk { get; set; }
        public string Details { get; set; }

        //RelationShips
        public List<Product> Products { get; set; }
        //foreing key 
        public int MunicipalityId { get; set; }
        [ForeignKey("MunicipalityId")]
        public Municipality Municipality { get; set; }
    }
}

AgriculturalSale/AgriculturalSale/Controllers/LocationController.cs
using AgriculturalSale.Data.Services;
using AgriculturalSale.Data.ViewModels;
using AgriculturalSale.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

namespace AgriculturalSale.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILocationService _service;

        public LocationController(ILocationService service)
        {

            this._service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await this._service.GetAllAsync(m => m.Municipality);
            return View(data);
        }

        //get create 
        public async Task<IActionResult> Create()
        {
            var locationDropDownsData = await this._service.GetNewLocationDropdownsValues();
            ViewBag.Municipalities = new SelectList(
                   locationDropDownsData.Municipalities, "Id", "name"
                );
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewLocationVM location)
        {
            if (!ModelState.IsValid)
            {
                var locationDropDownsdata = await this._service.GetNewLocationDropdownsValues();
                ViewBag.Municipalities = new SelectList(locationDropDownsdata.Municipalities, "Id", "name");
                return View(location);
            }

            await _service.AddNewLocationAsync(location);
            return RedirectToAction(nameof(Index));

        }

        //get details
        public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetLocationByIdAsync(id);
            return View(data);

        }

        public async Task<IActionResult> Edit(int id)
        {
            var locationDetails = await this._service.GetLocationByIdAsync(id);
            if (locationDetails == null) return View("NotFound");


            var response = new NewLocationVM()
            {
                Id = locationDetails.Id,
                SideWalk = locationDetails.SideWalk,
                Details = locationDetails.Details,
                MunicipalityId = locationDetails.MunicipalityId,
            };

            var locationDropDownsdata = await this._service.GetNewLocationDropdownsValues();
            ViewBag.Municipalities = new SelectList(locationDropDownsdata.Municipalities, "Id", "name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewLocationVM location)
        {
            if (id != location.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var locationDropDownsData = await this._service.GetNewLocationDropdownsValues();
                ViewBag.Municipalities = new SelectList(locationDropDownsData.Municipalities, "Id", "name");

                return View(location);
            }

            await _service.UpdateLocationAsync(location);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var locationDetails = await _service.GetLocationByIdAsync(id);
            if (locationDetails == null)
            {
                return View("NotFound");
            }
            return View(locationDetails);
        }

    }
}

AgriculturalSale/AgriculturalSale/Controllers/MunicipalityController.cs
using AgriculturalSale.Data.Services;
using AgriculturalSale.Models;
using Microsoft.AspNetCore.Mvc;

namespace AgriculturalSale.Controllers
{
    public class MunicipalityController : Controller
    {
        private readonly IMunicipalityService _service;

        public MunicipalityController(IMunicipalityService service)
        {
            this._service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await this._service.GetAllAsync();
            return View(data);
        }

        //Get : Municipality/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("name")] Municipality municipality)
        {
            if (!ModelState.IsValid)
            {
                return View(municipality);
            }
            await _service.AddAsync(municipality);
            return RedirectToAction(nameof(Index));
        }

        //get Municipality por id
        public async Task<IActionResult> Details(int id)
        {
            var municipalityDetails = await _service.GetByIdAsync(id);

            if (municipalityDetails == null) return View("NotFound");
            return View(municipalityDetails);

        }

        //Get for Edit
        public async Task<IActionResult> Edit(int id)
        {
            var municipalityDetails = await _service.GetByIdAsync(id);
            if (municipalityDetails == null) return View("NotFound");
            return View(municipalityDetails);

        }

        //Post for edit 
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, name")] Municipality municipality)
        {
            if (!ModelState.IsValid)
            {

                return View(municipality);

            }
            if (id == municipality.Id)
            {
                await _service.UpdateAsync(id, municipality);
                return RedirectToAction(nameof(Index));

            }
            return View(municipality);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var municipalityDetails = await _service.GetByIdAsync(id);
            if (municipalityDetails == null)
            {
                return View("NotFound");
            }
            return View(municipalityDetails);

        }

        [HttpPost, ActionName("Delete")]

        public async Task<ActionResult> DeleteConfirmed(int id, [Bind("Id,name")] Municipality municipality)
        {
            var municipalityDetails = await _service.GetByIdAsync(id);
            if (municipalityDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

AgriculturalSale/AgriculturalSale/Views/Location/Create.cshtml
@using AgriculturalSale.Data.ViewModels
@model NewLocationVM

@{

    ViewData["Title"] = "Create a new Location";
}

<div class="row">
    <div class="col-md-10 offset-1">
        <p>
            <h4>Create a new location</h4>
        </p>
        <div class="row">
            <div class="col-md-10 offset-1">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="SideWalk" class="control-label"></label>
                                <input asp-for="SideWalk" class="form-control" />
                                <span asp-validation-for="SideWalk" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MunicipalityId" class="control-label"></label>
                                <select asp-for="MunicipalityId" class="form-control" asp-items="ViewBag.Municipalities"></select>
                                <span asp-validation-for="MunicipalityId" class="text-danger"></span>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Details" class="control-label"></label>
                                    <textarea asp-for="Details" class="form-control"></textarea>
                                    <span asp-validation-for="Details" class="text-danger"></span>
                                </div>
                            </div>
                    </div>
                    <div class="form-group mt-2">
                        <input type="submit" value="Create" class="btn btn-outline-success" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AgriculturalSale/AgriculturalSale/Views/Location/Details.cshtml
@model Location

@{
    ViewData["Title"] = Model.SideWalk;
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p><h1>Details for @Model.SideWalk</h1></p>
        <div class="row">
            <div class="col-md-8 offset-2">

                <div class="form-group">
                    <b><label asp-for="SideWalk" class="control-label"></label></b>
                    <input asp-for="SideWalk" class="form-control" readonly />
                    <span asp-validation-for="SideWalk" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <b>Municipality: </b> <br /> 
                    <a asp-controller="Municipality" asp-action="Details" asp-route-id="@Model.MunicipalityId">
                        <i class="bi bi-geo-alt-fill">@Model.Municipality.name</i>
                    </a><br />
                    <span asp-validation-for="MunicipalityId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <b><label asp-for="Details" class="control-label"></label></b>
                    <textarea asp-for="Details" class="form-control" readonly></textarea>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a class="btn btn-outline-success float-end" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                </div>
            </div>
        </div>
    </div>
</div>

AgriculturalSale/AgriculturalSale/Views/Location/Edit.cshtml
@using AgriculturalSale.Data.ViewModels
@model NewLocationVM

@{
    ViewData["Title"] = "Update Location";
}

<div class="row">
    <div class="col-md-10 offset-1">
        <p>
            <h4>Update location</h4>
        </p>
        <div class="row">
            <div class="col-md-10 offset-1">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="SideWalk" class="control-label"></label>
                                <input asp-for="SideWalk" class="form-control" />
                                <span asp-validation-for="SideWalk" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MunicipalityId" class="control-label"></label>
                                <select asp-for="MunicipalityId" class="form-control" asp-items="ViewBag.Municipalities"></select>
                                <span asp-validation-for="MunicipalityId" class="text-danger"></span>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Details" class="control-label"></label>
                                    <textarea asp-for="Details" class="form-control"></textarea>
                                    <span asp-validation-for="Details" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group mt-2">
                            <input type="submit" value="Update" class="btn btn-outline-success float-end" />
                            <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>

AgriculturalSale/AgriculturalSale/Views/Location/Index.cshtml
@model IEnumerable<Location>
@{
    ViewData["Title"] = "List of Locations";

}

<div class="row">
    <table class=" col-md-8  table table-striped table-bordered">
        <thead class="cardh">
        <th>@Html.DisplayNameFor(m=> m.SideWalk)</th>
        <th>@Html.DisplayNameFor(m=> m.Details)</th>
        <th>@Html.DisplayNameFor(m=> m.MunicipalityId)</th>
        <th>Actions</th>
        </thead>
        <tbody>
            @foreach (var location in Model)
            {
                <tr>

                    <td class="align-middle">@location.SideWalk</td>
                    <td class="align-middle">@location.Details</td>
                    <td class="align-middle">@location.Municipality.name</td>
                    <td>
                        <a class="btn btn-outline-primary" style="margin-bottom: 5px" asp-action="Edit" asp-route-id="@location.Id"><i class="bi bi-pen"></i></a>
                        <br />
                        <a class="btn btn-outline-info" style="margin-bottom: 5px" asp-action="Details" asp-route-id="@location.Id"><i class="bi bi-info-circle"></i></a>
                        <br />
                        <a class="btn btn-outline-danger" style="margin-bottom: 5px" asp-action="Delete" asp-route-id="@location.Id"><i class="bi bi-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="text-dark mb-4" style="position:fixed; right: 25px; bottom : 35px;">
    <a asp-controller="Location" asp-action="Create" class="btn btn-success text-dark">
        <i class="bi bi-plus-circle"></i> Add New
    </a>

</div>