AgriculturalSale/AgriculturalSale/Controllers/ProductTypeController.cs
using AgriculturalSale.Data.Services;
using AgriculturalSale.Models;
using Microsoft.AspNetCore.Mvc;

namespace AgriculturalSale.Controllers
{
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeService _service;

        public ProductTypeController(IProductTypeService service)
        {
            this._service = service;
        }

        public async Task<IActionResult> Index() {
            var data = await this._service.GetAllAsync();
            return View(data);
        }

        //Get: ProductType/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind(" ImageUrl, Name, Details")] ProductType productType)
        {
            if (!ModelState.IsValid) {
                return View(productType);
            }
            await this._service.AddAsync(productType);
            return RedirectToAction(nameof(Index));

        }
        //get  product type 
        [HttpGet]
        public async Task<IActionResult> Details(int id) 
        { 
            var productTypeDetails = await this._service.GetByIdAsync(id);

            if (productTypeDetails == null) return View("NotFound");
            return View(productTypeDetails);
           
        }

        //get productType/Details

        public async Task<IActionResult> Edit(int id) {
        
            var productTypeDetails = await this._service.GetByIdAsync(id);
            if (productTypeDetails == null) return View("NotFound");
            return View(productTypeDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImageUrl,Name,Details")] ProductType productType) {
            if (!ModelState.IsValid) {
                return View(productType);
            }
            if (id == productType.Id)
            {
               await this._service.UpdateAsync(id, productType);
                return RedirectToAction(nameof(Index));  
            }
            return View(productType);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var productTypeDetails = await this._service.GetByIdAsync(id);
            if (productTypeDetails == null) {
                return View("NotFound");
            }
            return View(productTypeDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id, [Bind("Id, ImageUrl, Name, Details")] ProductType productType)
        {
            var productTypeDetails = await this._service.GetByIdAsync(id);
            if (productTypeDetails == null) return View("NotFound");

            await this._service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));

        }

    }
}

AgriculturalSale/AgriculturalSale/Views/ProductType/Create.cshtml
@model ProductType
@{
    ViewData["Title"] = "Create Product Type";
}
<div class="row text">
    <div class="col-md-8 offset-2">
        <p><h1>Add a new product type</h1></p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle" style="max-width: 100px " id="ImageUrl" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ImageUrl" class="control-label"></label>
                        <input asp-for="ImageUrl" class="form-control" />
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Details" class="control-label"></label>
                        <textarea asp-for="Details" class="form-control" > </textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImageUrl');
            output.src = $("#ImageUrl").val();
        })

        $("#ImageUrl").on("change", function () {
            var output = document.getElementById('ImageUrl');
            output.src = $(this).val();
        })
    </script>
}

AgriculturalSale/AgriculturalSale/Views/ProductType/Delete.cshtml
@model ProductType

@{
    ViewData["Title"] = "Delete Product Type";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p><h1>Delete confirmation for @Model.Name</h1></p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="width:100px; height:100px" id="ProfilePicturePreview" />
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl" class="control-label"></label>
                    <input asp-for="ImageUrl" class="form-control" readonly />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Details" class="control-label"></label>
                    <textarea asp-for="Details" class="form-control" readonly></textarea>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-end" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImageUrl');
            output.src = $("#ImageUrl").val();
        })
    </script>
}

AgriculturalSale/AgriculturalSale/Views/ProductType/Details.cshtml
@model ProductType

@{
    ViewData["Title"] = "@Model.FullName";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p><h1>Details for @Model.Name</h1></p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 100px" id="ProfilePicturePreview" />
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl" class="control-label"></label>
                    <input asp-for="ImageUrl" class="form-control" readonly />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Details" class="control-label"></label>
                    <textarea asp-for="Details" class="form-control" readonly></textarea>
                    <span asp-validation-for="Details" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a class="btn btn-outline-success float-end" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImageUrl');
            output.src = $("#ImageUrl").val();
        })
    </script>
}

AgriculturalSale/AgriculturalSale/Views/ProductType/Edit.cshtml
@model ProductType
@{
    ViewData["Title"] = "Update Product Type";
}
<div class="row text">
    <div class="col-md-8 offset-2">
        <p><h1>Update Product Type</h1></p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle" style="max-width: 100px " id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ImageUrl" class="control-label"></label>
                        <input asp-for="ImageUrl" class="form-control" />
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Details" class="control-label"></label>
                        <textarea asp-for="Details" class="form-control"> </textarea>
                        <span asp-validation-for="Details" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ImageUrl');
            output.src = $("#ImageUrl").val();
        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ImageUrl');
            output.src = $(this).val();
        })
    </script>
}

AgriculturalSale/AgriculturalSale/Views/ProductType/Index.cshtml
@model IEnumerable<ProductType>
@{
    ViewData["Title"] = "Product Type List";
}

<div class="row">
    <table class=" col-md-8  table table-striped table-bordered">
        <thead class="cardh">
        <th>@Html.DisplayNameFor(m=> m.ImageUrl)</th>
        <th>@Html.DisplayNameFor(m=> m.Name)</th>
        <th>@Html.DisplayNameFor(m=> m.Details)</th>
        <th>Actions</th>
        </thead>
        <tbody>
            @foreach (var pt in Model)
            {
                <tr>

                    <td class="align-middle"><img class="foto" src="@pt.ImageUrl" alt="@pt.Name"></td>
                    <td class="align-middle">@pt.Name</td>
                    <td class="align-middle">@pt.Details</td>
                    <td>
                        <a class="btn btn-outline-primary" style="margin-bottom: 5px" asp-action="Edit" asp-route-id="@pt.Id"><i class="bi bi-pen"></i></a>
                        <br />
                        <a class="btn btn-outline-info" style="margin-bottom: 5px" asp-action="Details" asp-route-id="@pt.Id"><i class="bi bi-info-circle"></i></a>
                        <br />
                        <a class="btn btn-outline-danger" style="margin-bottom: 5px" asp-action="Delete" asp-route-id="@pt.Id"><i class="bi bi-trash"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="text-dark mb-4" style="position:fixed; right: 25px; bottom : 35px;">
    <a asp-controller="ProductType" asp-action="Create" class="btn btn-success text-dark">
        <i class="bi bi-plus-circle"></i> Add New
    </a>

</div>